#!/usr/bin/env bash
export CONSUMER_KEY='YOUR CONSUMER_KEY HERE'
export CONSUMER_SECRET='YOUR CONSUMER_KEY HERE'
export ACCESS_TOKEN='YOUR ACCESS_TOKEN HERE'
export ACCESS_TOKEN_SECRET='YOUR ACCESS_TOKEN_SECRET HERE'
export OWNER='YOUR OWNER NAME HERE'
export OWNER_ID='YOUR OWNER_ID HERE'